Repository Devcourse-BE6-8-2-Team04/Kotlin_BackEnd, pull requests merged in 2025-09, with the labels that each got.

#51 refactor: 의류 엔티티 및 관련 기록 리팩토링
  src/main/java/com/team04/back/domain/cloth/cloth/dto/OutfitResponseDto.kt
  src/main/java/com/team04/back/domain/cloth/cloth/entity/ClothInfo.kt
  src/main/java/com/team04/back/domain/cloth/cloth/entity/Clothing.kt
  src/main/java/com/team04/back/domain/cloth/cloth/service/ClothService.kt
  src/main/java/com/team04/back/domain/history/history/entity/ClothRecommendationHistory.kt
  src/test/java/com/team04/back/common/fixture/FixtureFactory.java
  src/test/java/com/team04/back/domain/cloth/cloth/service/ClothServiceTest.java
Labels: enhancement

#57 히스토리기반 추천로직 구현
  src/main/java/com/team04/back/domain/cloth/cloth/controller/ClothController.kt
  src/main/java/com/team04/back/domain/cloth/cloth/dto/OutfitRecommendationResponseDto.kt
  src/main/java/com/team04/back/domain/cloth/cloth/dto/OutfitResponseDto.kt
  src/main/java/com/team04/back/domain/cloth/cloth/entity/ClothInfo.kt
  src/main/java/com/team04/back/domain/cloth/cloth/service/ClothService.kt
  src/main/java/com/team04/back/domain/history/history/entity/ClothRecommendationHistory.kt
  src/main/java/com/team04/back/domain/history/history/repository/ClothRecommendationHistoryRepository.kt
  src/test/java/com/team04/back/common/fixture/FixtureFactory.java
  src/test/java/com/team04/back/domain/cloth/cloth/controller/ClothControllerTest.java
  src/test/java/com/team04/back/domain/cloth/cloth/service/ClothServiceTest.java
  src/test/java/com/team04/back/domain/cloth/cloth/service/ClothServiceTest.kt
  src/test/java/com/team04/back/domain/history/history/entity/ClothRecommendationHistoryTest.kt
  src/test/java/com/team04/back/domain/weather/weather/service/WeatherServiceTest.kt
Labels: feature

#61 feature: 로그인 & 회원가입
  build.gradle.kts
  src/main/java/com/team04/back/domain/history/history/entity/ClothRecommendationHistory.kt
  src/main/java/com/team04/back/domain/member/member/controller/AuthController.kt
  src/main/java/com/team04/back/domain/member/member/controller/MemberController.kt
  src/main/java/com/team04/back/domain/member/member/dto/MemberDto.kt
  src/main/java/com/team04/back/domain/member/member/dto/MemberLoginResBody.kt
  src/main/java/com/team04/back/domain/member/member/dto/MemberWithUserIdDto.kt
  src/main/java/com/team04/back/domain/member/member/entity/Gender.kt
  src/main/java/com/team04/back/domain/member/member/entity/Member.kt
  src/main/java/com/team04/back/domain/member/member/entity/Tendency.kt
  src/main/java/com/team04/back/domain/member/member/repository/MemberRepository.kt
  src/main/java/com/team04/back/domain/member/member/service/AuthTokenService.kt
  src/main/java/com/team04/back/domain/member/member/service/MemberService.kt
  src/main/java/com/team04/back/domain/review/review/dto/ReviewDetailDto.kt
  src/main/java/com/team04/back/domain/review/review/dto/ReviewDto.kt
  src/main/java/com/team04/back/domain/review/review/entity/Review.kt
  src/main/java/com/team04/back/domain/review/review/service/ReviewService.kt
  src/main/java/com/team04/back/domain/user/user/entity/User.java
  src/main/java/com/team04/back/domain/user/user/repository/UserRepository.java
  src/main/java/com/team04/back/domain/user/user/service/UserService.java
  src/main/java/com/team04/back/domain/weather/weather/dto/WeatherInfoDto.kt
  src/main/java/com/team04/back/global/app/Appconfig.kt
  src/main/java/com/team04/back/global/config/JwtProperties.kt
  src/main/java/com/team04/back/global/jpa/entity/BaseEntity.kt
  src/main/java/com/team04/back/global/rq/Rq.kt
  src/main/java/com/team04/back/global/security/CustomAuthenticationFilter.kt
  src/main/java/com/team04/back/global/security/CustromUserDetailsService.kt
  src/main/java/com/team04/back/global/security/SecurityConfig.kt
  src/main/java/com/team04/back/global/security/SecurityUser.kt
  src/main/java/com/team04/back/standard/util/Ut.kt
  src/main/resources/application-secret.yml.default
  src/test/java/com/team04/back/common/fixture/FixtureFactory.java
  src/test/java/com/team04/back/domain/cloth/cloth/service/ClothServiceTest.kt
  src/test/java/com/team04/back/domain/history/history/entity/ClothRecommendationHistoryTest.kt
  src/test/java/com/team04/back/domain/history/history/service/ClothRecommendationHistoryServiceTest.kt
  src/test/java/com/team04/back/domain/review/review/controller/ReviewControllerTest.kt
  src/test/java/com/team04/back/domain/weather/weather/controller/WeatherControllerTest.kt
  src/test/kotlin/com/team04/back/domain/member/member/controller/MemberControllerTest.kt
Labels: enhancement, feature
